apiVersion: v1
kind: PersistentVolume
metadata:
  name: chromadb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: chromadb-storage
  hostPath:
    path: /data/vector_db/chroma_db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
  namespace: exaone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: chromadb-storage
  resources:
    requests:
      storage: 10Gi
