apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoint-server
  template:
    metadata:
      labels:
        app: endpoint-server
    spec:
      containers:
      - name: endpoint-server
        image: charlescr.azurecr.io/exaone/uipath-demo-endpoint:250318
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        env:
          - name: LLM_SERVER_URL
            value: http://vllm-server-service:8001/v1/chat/completions
          - name: LLM_MODEL
            value: LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct
          - name: VECTOR_DB_URL
            value: http://chromadb-server-service:8002

---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-server-service
spec:
  selector:
    app: endpoint-server
  ports:
    - port: 8000
      targetPort: 8000
