apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
  namespace: exaone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-server
  template:
    metadata:
      labels:
        app: vllm-server
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: vllm
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      containers:
      - name: vllm-server
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct --port 8001"
        ]
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
          - containerPort: 8001
            protocol: TCP
        volumeMounts:
        - name: cache-volume
          mountPath: /root/.cache/huggingface
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 120
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: vllm-server-service
  namespace: exaone
spec: 
  selector:
    app: vllm-server
  ports:
    - port: 8001
      targetPort: 8001
